### ISSUE TITLE
user dapat menghapus product yang disimpan - DELETE

### ISSUE THREAD

**Issue by agungape** [agungape/e-learning#8]

**Comment by are-one** [comment]
# Penjelasan Hasil:
Proses hapus data product sudah berhasil sy buat dan sy test di pc berhasil
dengan endpoint sebagai berikut:

`localhost:3000/product/:id`

ket: `:id` = id product yang ingin dihapus


# Contoh Hasil:
Misalkan inputan `localhost:3000/product/3`

### Hasil jika data berhasil dihapus
`
{
    "message": "Data berhasil dihapus",
    "status": 200
}
`

### Hasil jika data yang ingin dihapus tidak ditemukan
`
{
    "message": "Data tidak ditemukan.",
    "status": 404
}
`
